### ISSUE TITLE
Sample apk does not show any recent image 

### ISSUE THREAD

**Issue by franshua91** [amirarcane/recent-images#1]
Android 6.0.1
Nexus 6P

**Comment by amirarcane** [comment]
You're right, It was because of Android 6 new permissions method.
Check it again please.

**Comment by franshua91** [comment]
Hi, sorry I have tested it and it does not work yet.
![screenshot_20160528-112905](https://cloud.githubusercontent.com/assets/3586367/15626548/749691d0-24c7-11e6-802d-0c8256c547f6.png)

**Comment by amirarcane** [comment]
In your device settings, check the app permissions, agree them all and see if it solved.

**Comment by franshua91** [comment]
You are rigth. Sorry I forgot to check it. Thanks

**Comment by tuhin10** [comment]
I'm getting parse error for the sample.apk.  Android 6.0 OPO CM13
