### ISSUE TITLE
Camera image Not works in Xiaomi Redmi

### ISSUE THREAD

**Issue by ghost** [amirarcane/recent-images#16]
Hi! 
I try to run this app in Xiaomi Redmi2. The captured image does not show in ImageView. Uploaded gallery image only showed. But the captured image works for all mobiles except this mobile. 
The coding is:

if (resultCode == Activity.RESULT_OK) {
                    BitmapDrawable thumbnail = new BitmapDrawable(getResources(), data.getData().getPath());
                    image.setImageDrawable(thumbnail);
                }

Here onActivityResult Intent data got only null value in Redmi. So cannot upload captured image.

**Comment by amirarcane** [comment]
Hi David,

Thanks for your report, I will check it as soon as possible and tell you
the problem. If you have any further questions do not hesitate to contact
me.

Amirhossein Naghshzan

**Comment by amirarcane** [comment]
Hi,
Check sample project. Before calling camera intent, we set imageUri so in OnActivityResult method there is no need to get path of data, just code like below:

Bitmap bitmap = MediaStore.Images.Media.getBitmap(context.getContentResolver(), imageUri);
image.setImageBitmap(bitmap);

Check if it solve the problem.
