### ISSUE TITLE
Images take much time to load and sometimes dont even load!

### ISSUE THREAD

**Issue by mittalharsh54** [amirarcane/recent-images#17]
Images take much time to load and sometimes dont even load in some device.

**Comment by mittalharsh54** [comment]
Can you please tell about this if we can use any loader library. If yes then how?

**Comment by rayliverified** [comment]
This library does a fantastic job of loading images! Truth be told, I am probably going to "steal" the image loading code for my own project if it handles large images well. Here's why this library's image loading is so fantastic:
1. It does not use Glide or Picasso. ;)
2. Images are cached in the device. This feature is the kicker! The library takes quite a while to load images the first time the picker is launched but...
3. ...any time after that, images load instantly. What is so amazing is that I can scroll through dozens of photos and they all load near instantly after their thumbnail has been generated the first time. This library has the closest "iPhone" like image loading I have seen in an image picker library. 
4. @amirarcane even added a nice cleanupcache() function to help manage the cache :+1: 

IMO, using a image loading library like Glide or Picasso does not work as well as what is already in place here. The only way this library's implementation could be better is if you could kick off a background process to cache the first 10 recent images so images load instantly. Then we will have true parity with the iPhone!

**Comment by amirarcane** [comment]
@mittalharsh54: As @searchy2 mentioned, I believe it is the best way to load local images, loader libraries do great for loading online pictures, This is why I started to develop this library. 

@searchy2: Thanks for your encouragement and don't forget pull requests are welcomed 😉
