### ISSUE TITLE
Deleted images still load count in adapter

### ISSUE THREAD

**Issue by IRMobydick** [amirarcane/recent-images#18]
Hi there,
For uploading images to server after editing, we save them in temp folder and after successful upload process, we remove them.
But your library still list them, even without image!

how can deal with this?

**Comment by amirarcane** [comment]
Hi,
I added **cleanupCache** method to **RecentImages** class in version 1.0.5. Use it to clear the cache and set new adapter.

**Comment by IRMobydick** [comment]
👍 👍
