### ISSUE TITLE
Change Image loading view

### ISSUE THREAD

**Issue by tuhin10** [amirarcane/recent-images#2]
Default image loading view is very ugly how can I change. I can modify the and include it as local library.

![screenshot_2016-05-28-22-30-34](https://cloud.githubusercontent.com/assets/11805182/15628738/7a92f466-2526-11e6-9d96-7db372c35d0b.png)

**Comment by amirarcane** [comment]
recentimages/src/main/res/drawable/spinner_black_76.png
replace it with your own custom image.
