### ISSUE TITLE
Question: How can I set selected image in imageview

### ISSUE THREAD

**Issue by Badranh** [amirarcane/recent-images#28]

**Comment by amirarcane** [comment]
check the [sample](https://github.com/amirarcane/recent-images/blob/master/sample/src/main/java/com/amirarcane/sample/MainActivity.java) class. There is an `onItemClick` funcion.

**Comment by Badranh** [comment]
Uri imageUri = ContentUris.withAppendedId(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, l);
                Bitmap bitmap;
                try {
                    bitmap = MediaStore.Images.Media.getBitmap(contentResolver, imageUri);
                    imageView.setImageBitmap(bitmap);

                } catch (IOException e) {
                    e.printStackTrace();
                }
